name: Create Darkroom Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "darkroom.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
          path: "public/darkroom"
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "darkroom.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
